[dump-schema] found 18 tables: tbl_acc_status, tbl_action_admin, tbl_audit_log, tbl_balance, tbl_chat_message, tbl_chat_session, tbl_credits, tbl_daily_token, tbl_daily_usage, tbl_pricing, tbl_project, tbl_response, tbl_session, tbl_sync_state, tbl_topup_project, tbl_user, tbl_user_credit_transaction, tbl_user_role
-- ╔═══════════════════════════════════════════════════════════╗
-- ║ Phase 0 — Initial schema (auto-generated by dump-schema)  ║
-- ╚═══════════════════════════════════════════════════════════╝
-- Generated: 2026-05-26T07:18:14.497Z
-- Source: live DB (192.168.69.125/OpenAI_DB)
-- All statements are IF NOT EXISTS; safe to re-run.

BEGIN;

-- ── tbl_acc_status ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_acc_status (
    acc_status_id            INTEGER NOT NULL,
    acc_status               VARCHAR(100) NOT NULL,
    PRIMARY KEY (acc_status_id)
);

-- ── tbl_daily_token ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_daily_token (
    usage_date_th            DATE NOT NULL,
    project_id               VARCHAR(100) NOT NULL,
    start_time_th            BIGINT NOT NULL,
    end_time_th              BIGINT NOT NULL,
    start_time_utc           BIGINT NOT NULL,
    end_time_utc             BIGINT NOT NULL,
    model                    VARCHAR(20) NOT NULL,
    input_tokens             INTEGER DEFAULT 0 NOT NULL,
    output_tokens            INTEGER DEFAULT 0 NOT NULL,
    input_cached_tokens      INTEGER DEFAULT 0 NOT NULL,
    input_uncached_tokens    INTEGER DEFAULT 0 NOT NULL,
    input_text_tokens        INTEGER DEFAULT 0 NOT NULL,
    output_text_tokens       INTEGER DEFAULT 0 NOT NULL,
    input_cached_text_tokens INTEGER DEFAULT 0 NOT NULL,
    input_audio_tokens       INTEGER DEFAULT 0 NOT NULL,
    input_cached_audio_tokens INTEGER DEFAULT 0 NOT NULL,
    output_audio_tokens      INTEGER DEFAULT 0 NOT NULL,
    input_image_tokens       INTEGER DEFAULT 0 NOT NULL,
    output_image_tokens      INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (usage_date_th, project_id, model)
);

-- ── tbl_pricing ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_pricing (
    pricing_id               SERIAL NOT NULL,
    model                    VARCHAR(64) NOT NULL,
    input_cost               NUMERIC(10,6) NOT NULL,
    cached_cost              NUMERIC(10,6),
    output_cost              NUMERIC(10,6) NOT NULL,
    input_price              NUMERIC(10,6) NOT NULL,
    cached_price             NUMERIC(10,6),
    output_price             NUMERIC(10,6) NOT NULL,
    effective_from           TIMESTAMPTZ DEFAULT now() NOT NULL,
    effective_to             TIMESTAMPTZ,
    note                     TEXT,
    PRIMARY KEY (pricing_id),
    CONSTRAINT tbl_pricing_model_effective_from_key UNIQUE (model, effective_from)
);

-- ── tbl_project ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_project (
    project_id               VARCHAR(100) NOT NULL,
    project_name             VARCHAR(100) NOT NULL,
    project_api_key          TEXT,
    admin_api_key            TEXT,
    created_date             DATE DEFAULT CURRENT_DATE NOT NULL,
    description              TEXT DEFAULT ''::text,
    input_rate               NUMERIC(10,4) DEFAULT 0.50,
    output_rate              NUMERIC(10,4) DEFAULT 1.50,
    credit_limit             NUMERIC(12,2) DEFAULT 0,
    is_deleted               BOOLEAN DEFAULT false NOT NULL,
    deleted_at               TIMESTAMPTZ,
    openai_project_id        VARCHAR(64),
    openai_service_account_id VARCHAR(64),
    openai_synced_at         TIMESTAMPTZ,
    cached_input_rate        NUMERIC(10,4) DEFAULT 0.25,
    PRIMARY KEY (project_id)
);

-- ── tbl_sync_state ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_sync_state (
    id                       INTEGER NOT NULL,
    last_run_at              TIMESTAMPTZ,
    last_status              VARCHAR(20),
    last_error               TEXT,
    last_duration_ms         INTEGER,
    last_rows_inserted       INTEGER DEFAULT 0,
    rows_synced_total        BIGINT DEFAULT 0,
    updated_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- ── tbl_user_role ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_user_role (
    role_id                  INTEGER NOT NULL,
    role_des                 VARCHAR(100) NOT NULL,
    PRIMARY KEY (role_id)
);

-- ── tbl_balance ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_balance (
    project_id               VARCHAR(100) NOT NULL,
    project_credits          NUMERIC(12,2) DEFAULT 0 NOT NULL,
    top_up_date              DATE DEFAULT CURRENT_DATE NOT NULL,
    top_up_time              TIMESTAMP DEFAULT now() NOT NULL,
    user_id                  INTEGER NOT NULL,
    project_credits_amount   NUMERIC(12,2) DEFAULT 0 NOT NULL,
    PRIMARY KEY (project_id)
);

-- ── tbl_user ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_user (
    user_id                  SERIAL NOT NULL,
    project_id               VARCHAR(100),
    role_id                  INTEGER NOT NULL,
    username                 VARCHAR(100) NOT NULL,
    password                 VARCHAR(255) NOT NULL,
    name                     VARCHAR(50) NOT NULL,
    surname                  VARCHAR(50) DEFAULT ''::character varying NOT NULL,
    created_date             DATE DEFAULT CURRENT_DATE NOT NULL,
    acc_status_id            INTEGER NOT NULL,
    is_deleted               BOOLEAN DEFAULT false NOT NULL,
    deleted_at               TIMESTAMPTZ,
    failed_attempts          INTEGER DEFAULT 0 NOT NULL,
    locked_until             TIMESTAMPTZ,
    must_change_password     BOOLEAN DEFAULT false NOT NULL,
    daily_cap                NUMERIC(12,2),
    PRIMARY KEY (user_id)
);

-- ── tbl_user_credit_transaction ─────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_user_credit_transaction (
    transaction_id           BIGSERIAL NOT NULL,
    user_id                  INTEGER NOT NULL,
    project_id               VARCHAR(100),
    transaction_type         VARCHAR(20) NOT NULL,
    amount                   NUMERIC(12,4) NOT NULL,
    balance_before           NUMERIC(12,4),
    balance_after            NUMERIC(12,4),
    ref_type                 VARCHAR(20),
    ref_id                   BIGINT,
    note                     TEXT,
    created_by               INTEGER,
    created_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (transaction_id)
);

-- ── tbl_action_admin ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_action_admin (
    user_id                  INTEGER NOT NULL,
    project_id               VARCHAR(100),
    role_id                  INTEGER NOT NULL,
    edit_date                DATE DEFAULT CURRENT_DATE NOT NULL,
    edit_time                TIMESTAMP DEFAULT now() NOT NULL,
    id                       BIGSERIAL NOT NULL,
    action_type              VARCHAR(40),
    target_type              VARCHAR(20),
    target_id                INTEGER,
    change_json              JSONB,
    PRIMARY KEY (id)
);

-- ── tbl_audit_log ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_audit_log (
    user_id                  INTEGER,
    log_in_date              DATE DEFAULT CURRENT_DATE NOT NULL,
    log_in_time              TIMESTAMP DEFAULT now() NOT NULL,
    log_out_date             DATE,
    log_out_time             TIMESTAMP,
    id                       BIGSERIAL NOT NULL,
    event_type               VARCHAR(20),
    detail                   JSONB,
    ip                       VARCHAR(45),
    PRIMARY KEY (id)
);

-- ── tbl_chat_session ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_chat_session (
    session_id               BIGSERIAL NOT NULL,
    user_id                  INTEGER NOT NULL,
    title                    VARCHAR(200) DEFAULT 'New chat'::character varying NOT NULL,
    created_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    is_deleted               BOOLEAN DEFAULT false NOT NULL,
    message_count            INTEGER DEFAULT 0 NOT NULL,
    total_cost               NUMERIC(12,4) DEFAULT 0 NOT NULL,
    is_favorite              BOOLEAN DEFAULT false NOT NULL,
    PRIMARY KEY (session_id)
);

-- ── tbl_credits ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_credits (
    user_id                  INTEGER NOT NULL,
    project_id               VARCHAR(100) NOT NULL,
    user_credits             NUMERIC(12,2) DEFAULT 0 NOT NULL,
    PRIMARY KEY (user_id)
);

-- ── tbl_daily_usage ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_daily_usage (
    usage_date               DATE NOT NULL,
    user_id                  INTEGER NOT NULL,
    project_id               VARCHAR(100) NOT NULL,
    input_tokens             INTEGER DEFAULT 0 NOT NULL,
    cached_tokens            INTEGER DEFAULT 0 NOT NULL,
    output_tokens            INTEGER DEFAULT 0 NOT NULL,
    reasoning_tokens         INTEGER DEFAULT 0 NOT NULL,
    request_count            INTEGER DEFAULT 0 NOT NULL,
    total_cost               NUMERIC(12,4) DEFAULT 0 NOT NULL,
    total_price              NUMERIC(12,4) DEFAULT 0 NOT NULL,
    margin                   NUMERIC(12,4),
    first_seen_at            TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_updated_at          TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (usage_date, user_id)
);

-- ── tbl_response ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_response (
    response_id              VARCHAR(255) NOT NULL,
    project_id               VARCHAR(100) NOT NULL,
    model                    VARCHAR(20) NOT NULL,
    created_at               TIMESTAMP DEFAULT now() NOT NULL,
    input_param              TEXT DEFAULT ''::text NOT NULL,
    output_param             TEXT DEFAULT ''::text NOT NULL,
    input_tokens             INTEGER DEFAULT 0 NOT NULL,
    input_cached_tokens      INTEGER DEFAULT 0 NOT NULL,
    output_tokens            INTEGER DEFAULT 0 NOT NULL,
    output_reasoning_tokens  INTEGER DEFAULT 0 NOT NULL,
    total_tokens             INTEGER DEFAULT 0 NOT NULL,
    user_id                  INTEGER,
    PRIMARY KEY (response_id)
);

-- ── tbl_session ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_session (
    token                    VARCHAR(128) NOT NULL,
    user_id                  INTEGER NOT NULL,
    role                     VARCHAR(32) NOT NULL,
    expires_at               TIMESTAMPTZ NOT NULL,
    created_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    last_seen_at             TIMESTAMPTZ DEFAULT now() NOT NULL,
    csrf_token               VARCHAR(64),
    PRIMARY KEY (token)
);

-- ── tbl_topup_project ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_topup_project (
    id                       BIGSERIAL NOT NULL,
    project_id               VARCHAR(64) NOT NULL,
    user_id                  INTEGER NOT NULL,
    amount                   NUMERIC(12,2) NOT NULL,
    balance_before           NUMERIC(12,2) NOT NULL,
    balance_after            NUMERIC(12,2) NOT NULL,
    note                     TEXT,
    created_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- ── tbl_chat_message ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tbl_chat_message (
    message_id               BIGSERIAL NOT NULL,
    session_id               BIGINT NOT NULL,
    role                     VARCHAR(16) NOT NULL,
    content                  TEXT NOT NULL,
    created_at               TIMESTAMPTZ DEFAULT now() NOT NULL,
    input_tokens             INTEGER,
    output_tokens            INTEGER,
    cost                     NUMERIC(12,6),
    model                    VARCHAR(64),
    skill_id                 VARCHAR(64),
    PRIMARY KEY (message_id)
);

-- ── Foreign keys ───────────────────────────────────────────
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_balance' AND constraint_name='tbl_balance_project_id_fkey'
    ) THEN
        ALTER TABLE tbl_balance
            ADD CONSTRAINT tbl_balance_project_id_fkey
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user' AND constraint_name='tbl_user_acc_status_id_fkey'
    ) THEN
        ALTER TABLE tbl_user
            ADD CONSTRAINT tbl_user_acc_status_id_fkey
            FOREIGN KEY (acc_status_id)
            REFERENCES tbl_acc_status(acc_status_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user' AND constraint_name='tbl_user_project_id_fkey'
    ) THEN
        ALTER TABLE tbl_user
            ADD CONSTRAINT tbl_user_project_id_fkey
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user' AND constraint_name='tbl_user_role_id_fkey'
    ) THEN
        ALTER TABLE tbl_user
            ADD CONSTRAINT tbl_user_role_id_fkey
            FOREIGN KEY (role_id)
            REFERENCES tbl_user_role(role_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user_credit_transaction' AND constraint_name='tbl_user_credit_transaction_created_by_fkey'
    ) THEN
        ALTER TABLE tbl_user_credit_transaction
            ADD CONSTRAINT tbl_user_credit_transaction_created_by_fkey
            FOREIGN KEY (created_by)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user_credit_transaction' AND constraint_name='tbl_user_credit_transaction_project_id_fkey'
    ) THEN
        ALTER TABLE tbl_user_credit_transaction
            ADD CONSTRAINT tbl_user_credit_transaction_project_id_fkey
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_user_credit_transaction' AND constraint_name='tbl_user_credit_transaction_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_user_credit_transaction
            ADD CONSTRAINT tbl_user_credit_transaction_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_action_admin' AND constraint_name='tbl_action_admin_role_id_fkey'
    ) THEN
        ALTER TABLE tbl_action_admin
            ADD CONSTRAINT tbl_action_admin_role_id_fkey
            FOREIGN KEY (role_id)
            REFERENCES tbl_user_role(role_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_action_admin' AND constraint_name='tbl_action_admin_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_action_admin
            ADD CONSTRAINT tbl_action_admin_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_audit_log' AND constraint_name='tbl_audit_log_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_audit_log
            ADD CONSTRAINT tbl_audit_log_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_chat_session' AND constraint_name='tbl_chat_session_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_chat_session
            ADD CONSTRAINT tbl_chat_session_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
            ON DELETE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_credits' AND constraint_name='tbl_credits_project_id_fkey'
    ) THEN
        ALTER TABLE tbl_credits
            ADD CONSTRAINT tbl_credits_project_id_fkey
            FOREIGN KEY (project_id)
            REFERENCES tbl_balance(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_credits' AND constraint_name='tbl_credits_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_credits
            ADD CONSTRAINT tbl_credits_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_daily_usage' AND constraint_name='fk_daily_usage_project'
    ) THEN
        ALTER TABLE tbl_daily_usage
            ADD CONSTRAINT fk_daily_usage_project
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_daily_usage' AND constraint_name='fk_daily_usage_user'
    ) THEN
        ALTER TABLE tbl_daily_usage
            ADD CONSTRAINT fk_daily_usage_user
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_response' AND constraint_name='tbl_response_project_id_fkey'
    ) THEN
        ALTER TABLE tbl_response
            ADD CONSTRAINT tbl_response_project_id_fkey
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_response' AND constraint_name='tbl_response_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_response
            ADD CONSTRAINT tbl_response_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
            ON DELETE SET NULL
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_session' AND constraint_name='tbl_session_user_id_fkey'
    ) THEN
        ALTER TABLE tbl_session
            ADD CONSTRAINT tbl_session_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
            ON DELETE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_topup_project' AND constraint_name='tbl_topup_history_project_fk'
    ) THEN
        ALTER TABLE tbl_topup_project
            ADD CONSTRAINT tbl_topup_history_project_fk
            FOREIGN KEY (project_id)
            REFERENCES tbl_project(project_id)
            ON UPDATE CASCADE
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_topup_project' AND constraint_name='tbl_topup_history_user_fk'
    ) THEN
        ALTER TABLE tbl_topup_project
            ADD CONSTRAINT tbl_topup_history_user_fk
            FOREIGN KEY (user_id)
            REFERENCES tbl_user(user_id)
        ;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name='tbl_chat_message' AND constraint_name='tbl_chat_message_session_id_fkey'
    ) THEN
        ALTER TABLE tbl_chat_message
            ADD CONSTRAINT tbl_chat_message_session_id_fkey
            FOREIGN KEY (session_id)
            REFERENCES tbl_chat_session(session_id)
            ON DELETE CASCADE
        ;
    END IF;
END $$;

-- ── Indexes ────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS ix_daily_token_project_date ON public.tbl_daily_token USING btree (project_id, usage_date_th DESC);
CREATE INDEX IF NOT EXISTS idx_pricing_model_active ON public.tbl_pricing USING btree (model) WHERE (effective_to IS NULL);
CREATE INDEX IF NOT EXISTS idx_project_active ON public.tbl_project USING btree (project_id) WHERE (is_deleted = false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tbl_project_openai_project_id ON public.tbl_project USING btree (openai_project_id) WHERE (openai_project_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_user_active ON public.tbl_user USING btree (user_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_user_locked ON public.tbl_user USING btree (locked_until) WHERE (locked_until IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_user_project ON public.tbl_user USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS tbl_user_username_uniq ON public.tbl_user USING btree (username);
CREATE INDEX IF NOT EXISTS idx_uct_date ON public.tbl_user_credit_transaction USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_uct_project_date ON public.tbl_user_credit_transaction USING btree (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_uct_type_date ON public.tbl_user_credit_transaction USING btree (transaction_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_uct_user_date ON public.tbl_user_credit_transaction USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_admin_target ON public.tbl_action_admin USING btree (target_type, target_id) WHERE (target_type IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_action_admin_type ON public.tbl_action_admin USING btree (action_type) WHERE (action_type IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_action_admin_user_date ON public.tbl_action_admin USING btree (user_id, edit_date DESC);
CREATE INDEX IF NOT EXISTS idx_action_admin_user_time ON public.tbl_action_admin USING btree (user_id, edit_time DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_event ON public.tbl_audit_log USING btree (event_type, log_in_date DESC) WHERE (event_type IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_time ON public.tbl_audit_log USING btree (user_id, log_in_time DESC);
CREATE INDEX IF NOT EXISTS idx_chat_session_favorite ON public.tbl_chat_session USING btree (user_id, updated_at DESC) WHERE ((is_favorite = true) AND (is_deleted = false));
CREATE INDEX IF NOT EXISTS idx_chat_session_user_updated ON public.tbl_chat_session USING btree (user_id, updated_at DESC) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_credits_project ON public.tbl_credits USING btree (project_id);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON public.tbl_daily_usage USING btree (usage_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_usage_project_date ON public.tbl_daily_usage USING btree (project_id, usage_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_usage_user_date ON public.tbl_daily_usage USING btree (user_id, usage_date DESC);
CREATE INDEX IF NOT EXISTS idx_response_project_created ON public.tbl_response USING btree (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_response_user_created ON public.tbl_response USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_expires ON public.tbl_session USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_session_user ON public.tbl_session USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_topup_project_time ON public.tbl_topup_project USING btree (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_topup_user_time ON public.tbl_topup_project USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_message_session_created ON public.tbl_chat_message USING btree (session_id, created_at);

COMMIT;
[dump-schema] ✓ 18 tables emitted
